import type { DrillType, DifficultyLevel } from "@/types/database";

export interface SyntaxDrill {
  id: string;
  unitSlug: string;
  topic: string;
  drillType: DrillType;
  prompt: string;
  starterCode?: string;
  correctAnswer: string;
  acceptableAnswers?: string[];
  explanation: string;
  difficulty: DifficultyLevel;
}

export const syntaxDrills: SyntaxDrill[] = [
  {
    id: "declare-int",
    unitSlug: "primitive-types",
    topic: "Variable declarations",
    drillType: "type_from_memory",
    prompt: "Declare an int named age and initialize it to 16.",
    correctAnswer: "int age = 16;",
    explanation: "int declares the type, age is the identifier, and = 16; assigns the initial value.",
    difficulty: "intro",
  },
  {
    id: "declare-double",
    unitSlug: "primitive-types",
    topic: "Variable declarations",
    drillType: "type_from_memory",
    prompt: "Declare a double named price and initialize it to 4.99.",
    correctAnswer: "double price = 4.99;",
    explanation: "double stores decimal values; the literal 4.99 is already a double by default.",
    difficulty: "intro",
  },
  {
    id: "declare-boolean",
    unitSlug: "boolean-expressions-and-if-statements",
    topic: "Variable declarations",
    drillType: "type_from_memory",
    prompt: "Declare a boolean named isEnrolled and initialize it to true.",
    correctAnswer: "boolean isEnrolled = true;",
    explanation: "boolean variables may only hold true or false — never 0 or 1 as in some other languages.",
    difficulty: "intro",
  },
  {
    id: "declare-constant",
    unitSlug: "primitive-types",
    topic: "Constants",
    drillType: "type_from_memory",
    prompt: "Declare a constant int named MAX_SCORE equal to 100 that cannot be reassigned.",
    correctAnswer: "final int MAX_SCORE = 100;",
    explanation: "final prevents reassignment after initialization; constants are conventionally named in SCREAMING_SNAKE_CASE.",
    difficulty: "easy",
  },
  {
    id: "create-string",
    unitSlug: "using-objects",
    topic: "String methods",
    drillType: "type_from_memory",
    prompt: "Declare a String named greeting and initialize it to \"Hello\".",
    correctAnswer: 'String greeting = "Hello";',
    explanation: "String is a class, not a primitive, but literals can still be assigned directly without new.",
    difficulty: "intro",
  },
  {
    id: "modulus-expression",
    unitSlug: "primitive-types",
    topic: "Arithmetic expressions",
    drillType: "type_from_memory",
    prompt: "Write an expression that stores the remainder of dividing total by 3 into a variable named remainder.",
    correctAnswer: "int remainder = total % 3;",
    explanation: "% returns the remainder of integer division.",
    difficulty: "easy",
  },
  {
    id: "cast-double-to-int",
    unitSlug: "primitive-types",
    topic: "Casting",
    drillType: "type_from_memory",
    prompt: "Cast the double variable price to an int and store it in a new variable named dollars.",
    correctAnswer: "int dollars = (int) price;",
    explanation: "Casting a double to int truncates the decimal portion; it does not round.",
    difficulty: "easy",
  },
  {
    id: "compound-assignment",
    unitSlug: "primitive-types",
    topic: "Arithmetic expressions",
    drillType: "type_from_memory",
    prompt: "Increase the variable total by 5 using compound assignment.",
    correctAnswer: "total += 5;",
    explanation: "total += 5; is shorthand for total = total + 5;",
    difficulty: "intro",
  },
  {
    id: "if-statement",
    unitSlug: "boolean-expressions-and-if-statements",
    topic: "If statements",
    drillType: "type_from_memory",
    prompt: "Write an if statement that prints \"Passing\" when score is at least 70.",
    correctAnswer: 'if (score >= 70) {\n    System.out.println("Passing");\n}',
    explanation: ">= includes the boundary value 70 itself.",
    difficulty: "easy",
  },
  {
    id: "if-else-statement",
    unitSlug: "boolean-expressions-and-if-statements",
    topic: "If-else chains",
    drillType: "type_from_memory",
    prompt: "Write an if-else statement that prints \"Even\" if num is even and \"Odd\" otherwise.",
    correctAnswer: 'if (num % 2 == 0) {\n    System.out.println("Even");\n} else {\n    System.out.println("Odd");\n}',
    explanation: "num % 2 == 0 is the standard even-number test.",
    difficulty: "easy",
  },
  {
    id: "else-if-chain",
    unitSlug: "boolean-expressions-and-if-statements",
    topic: "Else-if chains",
    drillType: "type_from_memory",
    prompt: "Write an else-if chain assigning letter grades: \"A\" for score >= 90, \"B\" for score >= 80, else \"C\".",
    correctAnswer:
      'if (score >= 90) {\n    letter = "A";\n} else if (score >= 80) {\n    letter = "B";\n} else {\n    letter = "C";\n}',
    explanation: "Conditions are checked top to bottom; order from highest threshold to lowest matters.",
    difficulty: "medium",
  },
  {
    id: "de-morgans-law",
    unitSlug: "boolean-expressions-and-if-statements",
    topic: "Boolean expressions",
    drillType: "compare_similar_syntax",
    prompt: "Rewrite !(a && b) using De Morgan's law so the negation is distributed.",
    correctAnswer: "!a || !b",
    explanation: "De Morgan's law: !(a && b) is equivalent to !a || !b.",
    difficulty: "medium",
  },
  {
    id: "for-loop-basic",
    unitSlug: "iteration",
    topic: "For loops",
    drillType: "type_from_memory",
    prompt: "Write a for loop that prints the integers from 0 through 9.",
    correctAnswer: "for (int i = 0; i < 10; i++) {\n    System.out.println(i);\n}",
    explanation: "i < 10 stops after printing 9, since i becomes 10 and the condition fails.",
    difficulty: "easy",
  },
  {
    id: "while-loop-basic",
    unitSlug: "iteration",
    topic: "While loops",
    drillType: "type_from_memory",
    prompt: "Write a while loop that continues while score is less than 100.",
    correctAnswer: "while (score < 100) {\n    // loop body\n}",
    explanation: "The condition is checked before each iteration; the loop body must eventually change score.",
    difficulty: "easy",
  },
  {
    id: "nested-loop",
    unitSlug: "iteration",
    topic: "Nested loops",
    drillType: "type_from_memory",
    prompt: "Write nested for loops that print a 3x3 grid of asterisks, one row per line.",
    correctAnswer:
      'for (int row = 0; row < 3; row++) {\n    for (int col = 0; col < 3; col++) {\n        System.out.print("*");\n    }\n    System.out.println();\n}',
    explanation: "The inner loop completes fully for each iteration of the outer loop.",
    difficulty: "medium",
  },
  {
    id: "enhanced-for-loop",
    unitSlug: "arrays",
    topic: "Array traversal",
    drillType: "type_from_memory",
    prompt: "Write an enhanced for loop that prints every element of the int array scores.",
    correctAnswer: "for (int score : scores) {\n    System.out.println(score);\n}",
    explanation: "Enhanced for loops read each element but cannot modify the underlying array by index.",
    difficulty: "easy",
  },
  {
    id: "method-header",
    unitSlug: "writing-classes",
    topic: "Method headers",
    drillType: "method_header_drill",
    prompt: "Write a method header for a public, static method named max that takes two ints and returns an int.",
    correctAnswer: "public static int max(int a, int b)",
    explanation: "Order is: access modifier, static/instance, return type, name, parameter list.",
    difficulty: "medium",
  },
  {
    id: "constructor",
    unitSlug: "writing-classes",
    topic: "Constructors",
    drillType: "type_from_memory",
    prompt: "Write a constructor for a class Student that takes a String name and assigns it to an instance field this.name.",
    correctAnswer: "public Student(String name) {\n    this.name = name;\n}",
    explanation: "A constructor shares its class's name and has no return type, not even void.",
    difficulty: "medium",
  },
  {
    id: "create-array",
    unitSlug: "arrays",
    topic: "Arrays",
    drillType: "type_from_memory",
    prompt: "Declare an integer array named values with a length of 10.",
    correctAnswer: "int[] values = new int[10];",
    explanation: "new int[10] allocates 10 slots, each initialized to 0 by default.",
    difficulty: "easy",
  },
  {
    id: "traverse-array",
    unitSlug: "arrays",
    topic: "Array traversal",
    drillType: "type_from_memory",
    prompt: "Write an indexed for loop that prints every element of the array values.",
    correctAnswer: "for (int i = 0; i < values.length; i++) {\n    System.out.println(values[i]);\n}",
    explanation: "values.length is a field (no parentheses), unlike String's length() method.",
    difficulty: "easy",
  },
  {
    id: "create-arraylist",
    unitSlug: "arraylist",
    topic: "ArrayList",
    drillType: "type_from_memory",
    prompt: "Declare an ArrayList of Strings named names.",
    correctAnswer: "ArrayList<String> names = new ArrayList<String>();",
    acceptableAnswers: ["ArrayList<String> names = new ArrayList<>();"],
    explanation: "The diamond operator <> lets the compiler infer the type argument on the right-hand side.",
    difficulty: "easy",
  },
  {
    id: "traverse-arraylist",
    unitSlug: "arraylist",
    topic: "ArrayList",
    drillType: "type_from_memory",
    prompt: "Write an enhanced for loop that prints every element of the ArrayList<String> names.",
    correctAnswer: "for (String name : names) {\n    System.out.println(name);\n}",
    explanation: "ArrayList supports the enhanced for loop just like arrays do.",
    difficulty: "easy",
  },
  {
    id: "arraylist-add-remove",
    unitSlug: "arraylist",
    topic: "ArrayList",
    drillType: "type_from_memory",
    prompt: "Add \"Ada\" to the ArrayList names, then remove the element at index 0.",
    correctAnswer: 'names.add("Ada");\nnames.remove(0);',
    explanation: "remove(int index) removes by position; remove(Object o) removes by value — these are different overloads.",
    difficulty: "medium",
  },
  {
    id: "create-2d-array",
    unitSlug: "2d-arrays",
    topic: "2D arrays",
    drillType: "type_from_memory",
    prompt: "Declare a 2D int array named grid with 3 rows and 4 columns.",
    correctAnswer: "int[][] grid = new int[3][4];",
    explanation: "The first bracket is the number of rows, the second is the number of columns per row.",
    difficulty: "medium",
  },
  {
    id: "overridden-method",
    unitSlug: "inheritance",
    topic: "Method overriding",
    drillType: "type_from_memory",
    prompt: "Write an overridden toString() method that returns the String \"Animal\".",
    correctAnswer: '@Override\npublic String toString() {\n    return "Animal";\n}',
    explanation: "@Override isn't required but documents intent and lets the compiler catch signature mismatches.",
    difficulty: "medium",
  },
  {
    id: "recursive-method",
    unitSlug: "recursion",
    topic: "Recursion",
    drillType: "type_from_memory",
    prompt: "Write a recursive method factorial(int n) that returns n! for n >= 0.",
    correctAnswer:
      "public static int factorial(int n) {\n    if (n == 0) {\n        return 1;\n    }\n    return n * factorial(n - 1);\n}",
    explanation: "n == 0 is the base case; each recursive call moves n closer to 0.",
    difficulty: "hard",
  },
  {
    id: "equals-vs-double-equals",
    unitSlug: "using-objects",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "Write the correct way to compare two String objects, name1 and name2, for equal content.",
    correctAnswer: "name1.equals(name2)",
    explanation: "== compares references for objects; .equals() compares the actual content of the Strings.",
    difficulty: "medium",
  },
  {
    id: "length-field-vs-method",
    unitSlug: "arrays",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "Write the expression that gets the number of elements in the int array data.",
    correctAnswer: "data.length",
    explanation: "Arrays use the .length field (no parentheses).",
    difficulty: "easy",
  },
  {
    id: "length-method-string",
    unitSlug: "using-objects",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "Write the expression that gets the number of characters in the String word.",
    correctAnswer: "word.length()",
    explanation: "String uses the .length() method (with parentheses) — the opposite convention from arrays.",
    difficulty: "easy",
  },
  {
    id: "size-method-arraylist",
    unitSlug: "arraylist",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "Write the expression that gets the number of elements in the ArrayList<String> list.",
    correctAnswer: "list.size()",
    explanation: "ArrayList uses .size(), a third convention distinct from both array.length and String.length().",
    difficulty: "easy",
  },
  {
    id: "static-vs-instance",
    unitSlug: "writing-classes",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "Write a method header for a static method named createDefault that returns a new Student with no parameters.",
    correctAnswer: "public static Student createDefault()",
    explanation: "static methods belong to the class itself and can be called without an instance: Student.createDefault().",
    difficulty: "medium",
  },
  {
    id: "array-vs-arraylist",
    unitSlug: "arraylist",
    topic: "Compare similar syntax",
    drillType: "compare_similar_syntax",
    prompt: "State the key structural difference between an array and an ArrayList in one phrase.",
    correctAnswer: "An array has a fixed size; an ArrayList can grow and shrink.",
    explanation: "This is the core tradeoff the AP exam expects you to articulate when asked to justify a data structure choice.",
    difficulty: "easy",
  },
  {
    id: "plain-english-while",
    unitSlug: "iteration",
    topic: "Plain English to Java",
    drillType: "plain_english_to_java",
    prompt: "Create a while loop that continues while score is less than 100.",
    correctAnswer: "while (score < 100) {\n    // ...\n}",
    explanation: "Translate the condition directly: \"while score is less than 100\" becomes while (score < 100).",
    difficulty: "easy",
  },
  {
    id: "java-to-plain-english-loop",
    unitSlug: "iteration",
    topic: "Java to Plain English",
    drillType: "java_to_plain_english",
    prompt: "Explain in plain English what this loop does: for (int i = arr.length - 1; i >= 0; i--) { System.out.println(arr[i]); }",
    correctAnswer: "It prints the elements of arr in reverse order, from the last index down to the first.",
    explanation: "Starting at length - 1 and decrementing to 0 walks the array backward.",
    difficulty: "medium",
  },
];

export function drillsForUnit(unitSlug: string) {
  return syntaxDrills.filter((d) => d.unitSlug === unitSlug);
}
