-- ============================================================================
-- JavaChip — Seed data (generated by scripts/generate-seed.ts)
-- Seeds course content only. Demo accounts, classes, and assignments require
-- real auth.users rows — see database/seed/README.md.
-- ============================================================================

insert into courses (title, description, slug, published) values
  ('AP Computer Science A', 'JavaChip''s complete, original AP CSA curriculum across all ten College Board units.', 'ap-csa', true);

-- ---------------------------------------------------------------------------
-- Units
-- ---------------------------------------------------------------------------
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 1, 'Primitive Types', 'primitive-types', 'The arithmetic foundation of every Java program: how int, double, and boolean values are declared, stored, combined, and occasionally miscalculated.', 240, 1, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 2, 'Using Objects', 'using-objects', 'Working with existing classes: constructing objects, calling methods, and reasoning about String and Math behavior without writing a class from scratch yet.', 210, 2, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 3, 'Boolean Expressions and If Statements', 'boolean-expressions-and-if-statements', 'Making decisions in code: relational and logical operators, De Morgan''s laws, and how to structure conditionals that are correct and readable.', 200, 3, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 4, 'Iteration', 'iteration', 'Repetition with while and for loops: tracing loop state, avoiding off-by-one and infinite loops, and building accumulator patterns.', 230, 4, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 5, 'Writing Classes', 'writing-classes', 'Designing your own classes: instance variables, constructors, accessors and mutators, encapsulation, and the static keyword.', 240, 5, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 6, 'Array', 'arrays', 'Fixed-size collections: declaring, constructing, traversing, and running classic array algorithms like search, min/max, and reversal.', 210, 6, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 7, 'ArrayList', 'arraylist', 'A resizable, generic alternative to arrays: adding, removing, and safely traversing an ArrayList, plus autoboxing between int and Integer.', 200, 7, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 8, '2D Array', '2d-arrays', 'Grids and matrices: row-major and column-major traversal, nested loops, and boundary-aware neighbor algorithms.', 210, 8, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 9, 'Inheritance', 'inheritance', 'Building class hierarchies with extends, overriding methods, and understanding polymorphism through dynamic method dispatch.', 220, 9, true);
insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), 10, 'Recursion', 'recursion', 'Methods that call themselves: base cases, recursive cases, tracing the call stack, and comparing recursion to iteration.', 210, 10, true);

-- ---------------------------------------------------------------------------
-- Lessons (stubs for every unit; the first lesson of Unit 1 is fully authored)
-- ---------------------------------------------------------------------------
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'primitive-types'), 'Integer Division and Modulus', 'integer-division-and-modulus', 'Integer Division and Modulus — part of the Primitive Types unit.', 25, 0, true);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'primitive-types'), 'Variables, Assignment, and Casting', 'variables-and-casting', 'Variables, Assignment, and Casting — part of the Primitive Types unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'primitive-types'), 'The Math Class and Random Numbers', 'the-math-class', 'The Math Class and Random Numbers — part of the Primitive Types unit.', 20, 2, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'using-objects'), 'Constructing and Using Objects', 'constructing-objects', 'Constructing and Using Objects — part of the Using Objects unit.', 20, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'using-objects'), 'Comparing Strings with .equals()', 'comparing-strings-with-equals', 'Comparing Strings with .equals() — part of the Using Objects unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'Compound Boolean Expressions', 'compound-boolean-expressions', 'Compound Boolean Expressions — part of the Boolean Expressions and If Statements unit.', 20, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'If-Else Chains and Nested Conditionals', 'if-else-chains', 'If-Else Chains and Nested Conditionals — part of the Boolean Expressions and If Statements unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'iteration'), 'Writing and Tracing For Loops', 'writing-and-tracing-for-loops', 'Writing and Tracing For Loops — part of the Iteration unit.', 25, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'iteration'), 'While Loops and Sentinel Values', 'while-loops-and-sentinels', 'While Loops and Sentinel Values — part of the Iteration unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'writing-classes'), 'Writing Complete Java Classes', 'writing-complete-classes', 'Writing Complete Java Classes — part of the Writing Classes unit.', 30, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'writing-classes'), 'Encapsulation, this, and static', 'encapsulation-and-static', 'Encapsulation, this, and static — part of the Writing Classes unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'arrays'), 'Traversing Arrays', 'traversing-arrays', 'Traversing Arrays — part of the Array unit.', 25, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'arrays'), 'Search, Min/Max, and Reversal', 'array-algorithms', 'Search, Min/Max, and Reversal — part of the Array unit.', 25, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'arraylist'), 'Creating and Traversing an ArrayList', 'arraylist-basics', 'Creating and Traversing an ArrayList — part of the ArrayList unit.', 20, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'arraylist'), 'Removing Elements Safely', 'removing-during-traversal', 'Removing Elements Safely — part of the ArrayList unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = '2d-arrays'), 'Row-Major and Column-Major Traversal', '2d-array-traversal', 'Row-Major and Column-Major Traversal — part of the 2D Array unit.', 25, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = '2d-arrays'), 'Grid and Neighbor Algorithms', 'grid-neighbor-algorithms', 'Grid and Neighbor Algorithms — part of the 2D Array unit.', 25, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'inheritance'), 'Understanding Polymorphism', 'understanding-polymorphism', 'Understanding Polymorphism — part of the Inheritance unit.', 25, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'inheritance'), 'extends, super, and Constructor Chaining', 'extends-and-super', 'extends, super, and Constructor Chaining — part of the Inheritance unit.', 20, 1, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'recursion'), 'Tracing Recursive Methods', 'tracing-recursive-methods', 'Tracing Recursive Methods — part of the Recursion unit.', 25, 0, false);
insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = 'recursion'), 'Recursion on Arrays and Strings', 'recursion-on-arrays-and-strings', 'Recursion on Arrays and Strings — part of the Recursion unit.', 25, 1, false);

-- ---------------------------------------------------------------------------
-- Unit vocabulary
-- ---------------------------------------------------------------------------
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'primitive-types'), 'variable', 'A named storage location holding a value of a declared type.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'primitive-types'), 'constant', 'A variable declared final; its value cannot be reassigned after initialization.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'primitive-types'), 'cast', 'An explicit conversion of a value from one type to another, e.g. (int) 4.7.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'primitive-types'), 'operator precedence', 'The order in which operators are evaluated within an expression.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'primitive-types'), 'overflow', 'What happens when a computed value exceeds the range its type can represent.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'using-objects'), 'object', 'A runtime instance of a class, allocated in memory and accessed via a reference.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'using-objects'), 'constructor', 'A special method that initializes a newly created object.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'using-objects'), 'reference', 'A variable that stores the memory location of an object, not the object itself.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'using-objects'), 'alias', 'Two references pointing to the same object; changes through one are visible through the other.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'using-objects'), 'null', 'A reference that points to no object.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'short-circuit evaluation', 'Stopping evaluation of a Boolean expression as soon as the result is determined.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'De Morgan''s laws', 'Rules for distributing a negation over && and ||: !(a && b) == !a || !b.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'iteration'), 'accumulator', 'A variable that collects a running result (sum, count, product) across loop iterations.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'iteration'), 'sentinel value', 'A special input value that signals a loop to stop.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'writing-classes'), 'encapsulation', 'Bundling data with the methods that operate on it, and restricting direct access to that data.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'writing-classes'), 'this', 'A reference to the current object, used to disambiguate fields from parameters of the same name.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'arrays'), 'index', 'The zero-based position of an element within an array.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'arrays'), 'parallel arrays', 'Two or more arrays whose elements at the same index describe the same real-world entity.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'arraylist'), 'generic type', 'A type parameter, like <Integer>, that specifies what an ArrayList holds.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'arraylist'), 'autoboxing', 'Java''s automatic conversion of a primitive (int) into its wrapper object (Integer).');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = '2d-arrays'), 'row-major order', 'Traversing a 2D array one full row at a time before moving to the next row.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = '2d-arrays'), 'ragged array', 'A 2D array whose rows are not all the same length.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'inheritance'), 'polymorphism', 'The ability of a reference of a superclass type to invoke overridden behavior defined in a subclass.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'inheritance'), 'dynamic method dispatch', 'Java''s rule that an overridden method call resolves to the object''s actual runtime type, not its declared reference type.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'recursion'), 'base case', 'The condition under which a recursive method returns directly without calling itself again.');
insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = 'recursion'), 'call stack', 'The stack of in-progress method calls, each waiting on the recursive call beneath it to return.');

-- ---------------------------------------------------------------------------
-- Fully authored lesson: Integer Division and Modulus — one lesson_sections
-- row per part of the 26-part lesson structure.
-- ---------------------------------------------------------------------------
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'hook', 'Real-World Hook', '"Splitting a restaurant bill among friends, converting total minutes into hours and leftover minutes, or checking whether a number is even — all of these are integer division and modulus problems in disguise. AP CSA loves to test this exact idea, because it''s where a lot of Java''s behavior quietly differs from ordinary arithmetic."'::jsonb, 0);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'objectives', 'Learning Objectives', '["Predict the result of integer division between two int values","Predict the result of the % (modulus) operator, including with negative operands","Explain why 7 / 2 evaluates to 3, not 3.5, in Java","Use integer division and modulus together to decompose a quantity (e.g. minutes into hours and minutes)","Recognize integer-division bugs in AP-style code and MCQs"]'::jsonb, 1);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'prerequisites', 'Prerequisite Knowledge', '["Declaring and initializing int variables","Basic arithmetic operators: +, -, *, /"]'::jsonb, 2);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'vocabulary', 'Vocabulary', '[{"term":"integer division","definition":"Division between two int (or other integral) operands, which truncates any fractional part."},{"term":"modulus (%)","definition":"The remainder operator; a % b gives the remainder after dividing a by b."},{"term":"truncation","definition":"Discarding the fractional part of a number without rounding, always toward zero."},{"term":"operand","definition":"A value that an operator acts on — in a / b, a and b are the operands."}]'::jsonb, 3);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'explanation', 'Detailed Explanation', '["In Java, the / operator behaves differently depending on the types of its operands. When both operands are integers (int, long, short, byte), / performs integer division: it computes how many whole times the divisor fits into the dividend and discards — truncates — anything left over. 7 / 2 is not 3.5; it is 3.","Truncation in Java always rounds toward zero, not toward negative infinity. This matters for negative numbers: -7 / 2 evaluates to -3 (not -4), because Java truncates the true mathematical result of -3.5 toward zero.","The % operator returns the remainder of that division. 7 % 2 is 1, because 2 fits into 7 three times with 1 left over. Java guarantees that (a / b) * b + (a % b) always equals a, which is a useful way to sanity-check your understanding.","The sign of the result of % follows the sign of the left operand (the dividend) in Java. So -7 % 2 is -1, and 7 % -2 is 1. This trips up many students who expect the result to always be positive, or to follow the sign of the divisor as in some other languages.","If either operand is a double (or float), / performs ordinary floating-point division and does not truncate: 7.0 / 2 evaluates to 3.5. This is why casting matters — (double) 7 / 2 gives you 3.5, while (double) (7 / 2) gives you 3.0, because in the second expression the integer division happens before the cast is applied."]'::jsonb, 4);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'syntax_template', 'Syntax Template', '[{"title":"Integer division","code":"int quotient = a / b;   // truncates toward zero"},{"title":"Modulus","code":"int remainder = a % b;  // sign follows the dividend a"},{"title":"Forcing floating-point division","code":"double result = (double) a / b;  // cast BEFORE dividing"}]'::jsonb, 5);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'annotated_example', 'Annotated Java Example', '{"title":"Converting total minutes into hours and minutes","code":"public class TimeConverter {\n    public static void main(String[] args) {\n        int totalMinutes = 155;\n\n        int hours = totalMinutes / 60;\n        int minutesLeft = totalMinutes % 60;\n\n        System.out.println(hours + \" hours and \" + minutesLeft + \" minutes\");\n    }\n}"}'::jsonb, 6);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'line_by_line', 'Line-by-Line Breakdown', '[{"line":"int totalMinutes = 155;","explanation":"Declares and initializes an int holding the total number of minutes to convert."},{"line":"int hours = totalMinutes / 60;","explanation":"Integer division: 155 / 60 truncates to 2 — there are 2 full hours in 155 minutes."},{"line":"int minutesLeft = totalMinutes % 60;","explanation":"Modulus: 155 % 60 is 35 — the remainder after removing those 2 full hours (120 minutes)."},{"line":"System.out.println(hours + \" hours and \" + minutesLeft + \" minutes\");","explanation":"String concatenation with + builds and prints \"2 hours and 35 minutes\"."}]'::jsonb, 7);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'execution_trace', 'Visual Execution Trace', '["totalMinutes is initialized to 155.","155 / 60 is evaluated: 60 fits into 155 exactly 2 times (120), so hours becomes 2.","155 % 60 is evaluated: 155 − 120 = 35, so minutesLeft becomes 35.","The println statement concatenates and prints: 2 hours and 35 minutes."]'::jsonb, 8);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'variable_state_table', 'Variable-State Table', '[{"step":"After line 1","variables":{"totalMinutes":"155","hours":"—","minutesLeft":"—"}},{"step":"After line 2","variables":{"totalMinutes":"155","hours":"2","minutesLeft":"—"}},{"step":"After line 3","variables":{"totalMinutes":"155","hours":"2","minutesLeft":"35"}}]'::jsonb, 9);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'memory_note', 'Memory / Reference Note', '"int and double are primitive types, so hours, minutesLeft, and totalMinutes each store their value directly in a stack variable slot — there is no separate object on the heap and no reference to trace here. (Reference-diagram tracing becomes relevant starting in Unit 2, once we''re storing objects like String.)"'::jsonb, 10);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'common_mistakes', 'Common Mistakes', '["Expecting 7 / 2 to produce 3.5 when both operands are int — it produces 3.","Assuming % always returns a non-negative result — in Java its sign follows the dividend.","Casting after dividing, e.g. (double) (7 / 2), which still performs integer division first and only converts the already-truncated 3 to 3.0.","Dividing by zero with integer operands, which throws ArithmeticException at runtime rather than producing infinity (unlike floating-point division by zero, which produces Infinity or NaN)."]'::jsonb, 11);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'compiler_errors', 'Compiler-Error Examples', '[{"code":"int average = totalScore / count","error":"'';'' expected","fix":"Add the missing semicolon: int average = totalScore / count;"}]'::jsonb, 12);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'logic_errors', 'Logic-Error Examples', '[{"code":"int total = 10;\nint count = 4;\ndouble average = total / count;\nSystem.out.println(average);","issue":"Prints 2.0 instead of 2.5 — total / count performs integer division (10 / 4 truncates to 2) before that int result of 2 is widened to the double 2.0.","fix":"Cast at least one operand to double before dividing: double average = (double) total / count;"}]'::jsonb, 13);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'predict_output', 'Predict-the-Output Questions', '[{"code":"System.out.println(17 / 5);","answer":"3","explanation":"Integer division truncates 3.4 down to 3."},{"code":"System.out.println(17 % 5);","answer":"2","explanation":"17 minus (3 × 5) leaves a remainder of 2."},{"code":"System.out.println(-9 / 4);","answer":"-2","explanation":"-2.25 truncates toward zero, to -2, not -3."},{"code":"System.out.println(-9 % 4);","answer":"-1","explanation":"(-9 / 4) * 4 + (-9 % 4) must equal -9: (-2 * 4) + r = -9, so r = -1."}]'::jsonb, 14);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'fill_in_code', 'Fill-in-the-Code Questions', '[{"prompt":"Complete the code so it prints how many full dozens are in `eggCount`, and how many eggs are left over.","code":"int eggCount = 50;\nint dozens = eggCount ____ 12;\nint leftover = eggCount ____ 12;","answer":"dozens = eggCount / 12;  leftover = eggCount % 12;"}]'::jsonb, 15);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'code_ordering', 'Code-Ordering Activity', '{"instructions":"Arrange these lines so the program correctly prints the number of whole $10 bills and the leftover change for a purchase of totalCents cents converted to dollars.","lines":["System.out.println(bills + \" bills, \" + remainder + \" left over\");","int totalDollars = totalCents / 100;","int bills = totalDollars / 10;","int remainder = totalDollars % 10;"],"correctOrder":[1,2,3,0]}'::jsonb, 16);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'error_correction', 'Error-Correction Activity', '{"brokenCode":"int secondsPerDay = 86400;\nint hours = secondsPerDay / 60 / 60;\ndouble averageHourFraction = hours / 24;\nSystem.out.println(averageHourFraction);","bug":"hours / 24 is int / int, so it truncates to 0 before ever becoming a double — averageHourFraction always prints 0.0 no matter the input.","fixedCode":"int secondsPerDay = 86400;\nint hours = secondsPerDay / 60 / 60;\ndouble averageHourFraction = (double) hours / 24;\nSystem.out.println(averageHourFraction);"}'::jsonb, 17);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'coding_challenge', 'Short Coding Challenge', '{"prompt":"Write a method secondsToClock(int totalSeconds) that returns a String formatted as \"H:MM:SS\" (minutes and seconds always show as two digits) representing totalSeconds converted into hours, minutes, and seconds.","starterCode":"public static String secondsToClock(int totalSeconds) {\n    // your code here\n}","sampleSolution":"public static String secondsToClock(int totalSeconds) {\n    int hours = totalSeconds / 3600;\n    int minutes = (totalSeconds % 3600) / 60;\n    int seconds = totalSeconds % 60;\n    return hours + \":\" + String.format(\"%02d\", minutes) + \":\" + String.format(\"%02d\", seconds);\n}"}'::jsonb, 18);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'mcq_mini_set', 'MCQ Mini-Set', '[{"prompt":"What is the value of expr after the following code runs?","code":"int expr = (13 / 4) + (13 % 4);","choices":[{"label":"A","text":"3","correct":false,"explanation":"That''s just 13 / 4 alone (the quotient); the expression also adds the remainder."},{"label":"B","text":"4","correct":true,"explanation":"13 / 4 truncates to 3, and 13 % 4 is 1 (13 − 12). 3 + 1 = 4."},{"label":"C","text":"13","correct":false,"explanation":"(a / b) + (a % b) does not reconstruct a in general — that identity requires multiplying the quotient by b first: (a / b) * b + (a % b) == a."},{"label":"D","text":"16","correct":false,"explanation":"This would result from adding 13 and something, not from combining the quotient and remainder correctly."}]}]'::jsonb, 19);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'reflection', 'Reflection', '["Where did your prediction differ from Java''s actual output, and why?","Which rule — truncation direction, or the sign of %— would you have gotten wrong before this lesson?","What real-world conversion (time, money, units) could you model with / and % together?"]'::jsonb, 20);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'mastery_check', 'Mastery Check', '["I can predict the output of int / int division without running the code.","I can predict the sign of a % b for negative a or negative b.","I know where to place a cast to force floating-point division.","I can combine / and % to decompose a total into units and a remainder."]'::jsonb, 21);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'summary', 'Summary', '"Integer division truncates toward zero and discards the remainder; modulus recovers that remainder, with a sign that follows the dividend. Casting to double before dividing — not after — is what forces true floating-point division. This pairing shows up constantly in AP CSA problems that decompose a quantity into larger units and leftover amounts."'::jsonb, 22);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'related_links', 'Related Reference Links', '[{"label":"Reference: Arithmetic Operators","href":"/student/reference?entry=arithmetic-operators"},{"label":"Reference: Casting","href":"/student/reference?entry=casting"}]'::jsonb, 23);
insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values ((select id from lessons where slug = 'integer-division-and-modulus'), 'next_lesson', 'Suggested Next Lesson', '{"label":"Variables, Assignment, and Casting","href":"/student/units/primitive-types/lessons/variables-and-casting"}'::jsonb, 24);

-- ---------------------------------------------------------------------------
-- Java Reference Library entries (stored as syntax_templates)
-- ---------------------------------------------------------------------------
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Primitive Types', 'Arithmetic Operators', 'The operators +, -, *, /, and % combine numeric operands. / and % behave differently for integer vs. floating-point operands.', 'a + b   a - b   a * b   a / b   a % b', 'int quotient = 17 / 5;   // 3
int remainder = 17 % 5;  // 2', 'Expecting int / int to produce a decimal result.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Primitive Types', 'Casting', 'An explicit conversion of a value from one type to another, written as (type) value.', '(int) doubleValue
(double) intValue', 'double price = 4.75;
int dollars = (int) price;  // 4, not rounded', 'Assuming a cast rounds to the nearest value instead of truncating.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Using Objects', 'Core String Methods', 'String provides methods for inspecting and deriving new Strings: length(), substring(), indexOf(), equals(), and more. Strings are immutable — these methods never modify the original String.', 'str.length()
str.substring(start, end)
str.indexOf(target)
str.equals(other)', 'String word = "computer";
int len = word.length();       // 8
String sub = word.substring(0, 4); // "comp"', 'Using == instead of .equals() to compare String content.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Iteration', 'For Loop', 'A loop with an initialization, condition, and update clause, ideal when the number of iterations is known in advance.', 'for (int i = 0; i < n; i++) {
    // body
}', 'for (int i = 0; i < 5; i++) {
    System.out.println(i);
}
// prints 0 1 2 3 4', 'Using <= n instead of < n, causing one extra iteration.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('ArrayList', 'Core ArrayList Methods', 'ArrayList<E> supports add, remove, get, set, and size for managing a resizable, generically-typed collection.', 'list.add(value)
list.get(index)
list.set(index, value)
list.remove(index)
list.size()', 'ArrayList<String> names = new ArrayList<>();
names.add("Ada");
names.add("Al");
names.remove(0);
// names is now ["Al"]', 'Confusing remove(int index) with remove(Object o) — remove(1) removes the element at index 1, not the value 1.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Inheritance', 'extends and super', 'A subclass inherits fields and methods from its superclass using extends, and can call the superclass''s constructor or methods using super.', 'public class Dog extends Animal {
    public Dog(String name) {
        super(name);
    }
}', 'class Animal {
    protected String name;
    public Animal(String name) { this.name = name; }
}
class Dog extends Animal {
    public Dog(String name) { super(name); }
}', 'Forgetting that super(...) must be the first statement in a subclass constructor.', 'easy');
insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values ('Errors', 'Common Runtime Errors', 'Exceptions thrown while a program executes, as opposed to compiler errors caught before the program runs.', 'NullPointerException
ArrayIndexOutOfBoundsException
ArithmeticException
ClassCastException', 'int[] arr = new int[3];
System.out.println(arr[5]); // ArrayIndexOutOfBoundsException', 'Confusing a runtime exception with a compiler error — this code compiles fine and fails only when it executes.', 'easy');

-- ---------------------------------------------------------------------------
-- Syntax Café drills
-- ---------------------------------------------------------------------------
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Variable declarations', 'type_from_memory', 'Declare an int named age and initialize it to 16.', null, 'int age = 16;', 'int declares the type, age is the identifier, and = 16; assigns the initial value.', 'intro');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Variable declarations', 'type_from_memory', 'Declare a double named price and initialize it to 4.99.', null, 'double price = 4.99;', 'double stores decimal values; the literal 4.99 is already a double by default.', 'intro');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'Variable declarations', 'type_from_memory', 'Declare a boolean named isEnrolled and initialize it to true.', null, 'boolean isEnrolled = true;', 'boolean variables may only hold true or false — never 0 or 1 as in some other languages.', 'intro');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Constants', 'type_from_memory', 'Declare a constant int named MAX_SCORE equal to 100 that cannot be reassigned.', null, 'final int MAX_SCORE = 100;', 'final prevents reassignment after initialization; constants are conventionally named in SCREAMING_SNAKE_CASE.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'using-objects'), 'String methods', 'type_from_memory', 'Declare a String named greeting and initialize it to "Hello".', null, 'String greeting = "Hello";', 'String is a class, not a primitive, but literals can still be assigned directly without new.', 'intro');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Arithmetic expressions', 'type_from_memory', 'Write an expression that stores the remainder of dividing total by 3 into a variable named remainder.', null, 'int remainder = total % 3;', '% returns the remainder of integer division.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Casting', 'type_from_memory', 'Cast the double variable price to an int and store it in a new variable named dollars.', null, 'int dollars = (int) price;', 'Casting a double to int truncates the decimal portion; it does not round.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'primitive-types'), 'Arithmetic expressions', 'type_from_memory', 'Increase the variable total by 5 using compound assignment.', null, 'total += 5;', 'total += 5; is shorthand for total = total + 5;', 'intro');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'If statements', 'type_from_memory', 'Write an if statement that prints "Passing" when score is at least 70.', null, 'if (score >= 70) {
    System.out.println("Passing");
}', '>= includes the boundary value 70 itself.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'If-else chains', 'type_from_memory', 'Write an if-else statement that prints "Even" if num is even and "Odd" otherwise.', null, 'if (num % 2 == 0) {
    System.out.println("Even");
} else {
    System.out.println("Odd");
}', 'num % 2 == 0 is the standard even-number test.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'Else-if chains', 'type_from_memory', 'Write an else-if chain assigning letter grades: "A" for score >= 90, "B" for score >= 80, else "C".', null, 'if (score >= 90) {
    letter = "A";
} else if (score >= 80) {
    letter = "B";
} else {
    letter = "C";
}', 'Conditions are checked top to bottom; order from highest threshold to lowest matters.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'Boolean expressions', 'compare_similar_syntax', 'Rewrite !(a && b) using De Morgan''s law so the negation is distributed.', null, '!a || !b', 'De Morgan''s law: !(a && b) is equivalent to !a || !b.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'iteration'), 'For loops', 'type_from_memory', 'Write a for loop that prints the integers from 0 through 9.', null, 'for (int i = 0; i < 10; i++) {
    System.out.println(i);
}', 'i < 10 stops after printing 9, since i becomes 10 and the condition fails.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'iteration'), 'While loops', 'type_from_memory', 'Write a while loop that continues while score is less than 100.', null, 'while (score < 100) {
    // loop body
}', 'The condition is checked before each iteration; the loop body must eventually change score.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'iteration'), 'Nested loops', 'type_from_memory', 'Write nested for loops that print a 3x3 grid of asterisks, one row per line.', null, 'for (int row = 0; row < 3; row++) {
    for (int col = 0; col < 3; col++) {
        System.out.print("*");
    }
    System.out.println();
}', 'The inner loop completes fully for each iteration of the outer loop.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arrays'), 'Array traversal', 'type_from_memory', 'Write an enhanced for loop that prints every element of the int array scores.', null, 'for (int score : scores) {
    System.out.println(score);
}', 'Enhanced for loops read each element but cannot modify the underlying array by index.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'writing-classes'), 'Method headers', 'method_header_drill', 'Write a method header for a public, static method named max that takes two ints and returns an int.', null, 'public static int max(int a, int b)', 'Order is: access modifier, static/instance, return type, name, parameter list.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'writing-classes'), 'Constructors', 'type_from_memory', 'Write a constructor for a class Student that takes a String name and assigns it to an instance field this.name.', null, 'public Student(String name) {
    this.name = name;
}', 'A constructor shares its class''s name and has no return type, not even void.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arrays'), 'Arrays', 'type_from_memory', 'Declare an integer array named values with a length of 10.', null, 'int[] values = new int[10];', 'new int[10] allocates 10 slots, each initialized to 0 by default.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arrays'), 'Array traversal', 'type_from_memory', 'Write an indexed for loop that prints every element of the array values.', null, 'for (int i = 0; i < values.length; i++) {
    System.out.println(values[i]);
}', 'values.length is a field (no parentheses), unlike String''s length() method.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arraylist'), 'ArrayList', 'type_from_memory', 'Declare an ArrayList of Strings named names.', null, 'ArrayList<String> names = new ArrayList<String>();', 'The diamond operator <> lets the compiler infer the type argument on the right-hand side.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arraylist'), 'ArrayList', 'type_from_memory', 'Write an enhanced for loop that prints every element of the ArrayList<String> names.', null, 'for (String name : names) {
    System.out.println(name);
}', 'ArrayList supports the enhanced for loop just like arrays do.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arraylist'), 'ArrayList', 'type_from_memory', 'Add "Ada" to the ArrayList names, then remove the element at index 0.', null, 'names.add("Ada");
names.remove(0);', 'remove(int index) removes by position; remove(Object o) removes by value — these are different overloads.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = '2d-arrays'), '2D arrays', 'type_from_memory', 'Declare a 2D int array named grid with 3 rows and 4 columns.', null, 'int[][] grid = new int[3][4];', 'The first bracket is the number of rows, the second is the number of columns per row.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'inheritance'), 'Method overriding', 'type_from_memory', 'Write an overridden toString() method that returns the String "Animal".', null, '@Override
public String toString() {
    return "Animal";
}', '@Override isn''t required but documents intent and lets the compiler catch signature mismatches.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'recursion'), 'Recursion', 'type_from_memory', 'Write a recursive method factorial(int n) that returns n! for n >= 0.', null, 'public static int factorial(int n) {
    if (n == 0) {
        return 1;
    }
    return n * factorial(n - 1);
}', 'n == 0 is the base case; each recursive call moves n closer to 0.', 'hard');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'using-objects'), 'Compare similar syntax', 'compare_similar_syntax', 'Write the correct way to compare two String objects, name1 and name2, for equal content.', null, 'name1.equals(name2)', '== compares references for objects; .equals() compares the actual content of the Strings.', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arrays'), 'Compare similar syntax', 'compare_similar_syntax', 'Write the expression that gets the number of elements in the int array data.', null, 'data.length', 'Arrays use the .length field (no parentheses).', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'using-objects'), 'Compare similar syntax', 'compare_similar_syntax', 'Write the expression that gets the number of characters in the String word.', null, 'word.length()', 'String uses the .length() method (with parentheses) — the opposite convention from arrays.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arraylist'), 'Compare similar syntax', 'compare_similar_syntax', 'Write the expression that gets the number of elements in the ArrayList<String> list.', null, 'list.size()', 'ArrayList uses .size(), a third convention distinct from both array.length and String.length().', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'writing-classes'), 'Compare similar syntax', 'compare_similar_syntax', 'Write a method header for a static method named createDefault that returns a new Student with no parameters.', null, 'public static Student createDefault()', 'static methods belong to the class itself and can be called without an instance: Student.createDefault().', 'medium');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'arraylist'), 'Compare similar syntax', 'compare_similar_syntax', 'State the key structural difference between an array and an ArrayList in one phrase.', null, 'An array has a fixed size; an ArrayList can grow and shrink.', 'This is the core tradeoff the AP exam expects you to articulate when asked to justify a data structure choice.', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'iteration'), 'Plain English to Java', 'plain_english_to_java', 'Create a while loop that continues while score is less than 100.', null, 'while (score < 100) {
    // ...
}', 'Translate the condition directly: "while score is less than 100" becomes while (score < 100).', 'easy');
insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = 'iteration'), 'Java to Plain English', 'java_to_plain_english', 'Explain in plain English what this loop does: for (int i = arr.length - 1; i >= 0; i--) { System.out.println(arr[i]); }', null, 'It prints the elements of arr in reverse order, from the last index down to the first.', 'Starting at length - 1 and decrementing to 0 walks the array backward.', 'medium');

-- ---------------------------------------------------------------------------
-- MCQ Question Bank
-- ---------------------------------------------------------------------------
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'primitive-types'), 'Operator precedence', 'What is printed?', 'int result = 5 + 3 * 2;
System.out.println(result);', '* has higher precedence than +, so 3 * 2 evaluates first (6), then 5 + 6 = 11.', 'easy', 45, ARRAY['operator precedence'], 'Evaluating strictly left to right instead of respecting operator precedence.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '16', false, 'This would be the result only if + were evaluated before *, which is not Java''s precedence.', 0),
  ('B', '11', true, '* has higher precedence than +, so 3 * 2 evaluates first (6), then 5 + 6 = 11.', 1),
  ('C', '13', false, 'This doesn''t correspond to any valid evaluation order of this expression.', 2),
  ('D', '10', false, 'This would require dropping a term entirely.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'primitive-types'), 'Integer division and modulus', 'What is printed?', 'int x = 7;
int y = 2;
System.out.println(x / y + x % y);', 'x / y truncates to 3, and x % y is 1, so 3 + 1 = 4.', 'easy', 50, ARRAY['integer division', 'modulus'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '3', false, 'This is only x / y; the expression also adds x % y.', 0),
  ('B', '4', true, 'x / y truncates to 3, and x % y is 1, so 3 + 1 = 4.', 1),
  ('C', '3.5', false, 'int / int never produces a fractional result in Java.', 2),
  ('D', '1', false, 'This is only x % y, ignoring the quotient term.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'primitive-types'), 'Casting', 'What is printed?', 'double d = (double) 9 / 4;
System.out.println(d);', 'Casting 9 to double before dividing forces floating-point division: 9.0 / 4 = 2.25.', 'medium', 60, ARRAY['casting', 'integer division'], 'Believing (double) (9 / 4) and (double) 9 / 4 are equivalent because both involve a cast and a division.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '2.25', true, 'Casting 9 to double before dividing forces floating-point division: 9.0 / 4 = 2.25.', 0),
  ('B', '2.0', false, 'This would be the result of (double) (9 / 4) — casting AFTER integer division already truncated the value.', 1),
  ('C', '2', false, 'A double variable always prints with a decimal point in Java, so a bare 2 is not valid output for this type.', 2),
  ('D', '2.5', false, '9 / 4 is not 2.5; that would be the result of 10 / 4.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'using-objects'), 'Object references', 'What is printed?', 'String s1 = "cat";
String s2 = new String("cat");
System.out.println(s1 == s2);', 's1 and s2 refer to two different String objects in memory, even though their contents are identical, so == (reference comparison) is false.', 'medium', 60, ARRAY['object references', 'string comparison'], 'Assuming == compares String content the way .equals() does.', 'Ask what == actually compares for object types, not primitive types.', true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'true', false, '== compares references, and new String("cat") deliberately creates a distinct object from the interned literal "cat".', 0),
  ('B', 'false', true, 's1 and s2 refer to two different String objects in memory, even though their contents are identical, so == (reference comparison) is false.', 1),
  ('C', 'It does not compile.', false, 'This is valid Java; == is legal (if often misleading) on any two reference types.', 2),
  ('D', 'It throws a runtime exception.', false, 'Comparing references with == never throws; it simply returns true or false.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'writing-classes'), 'this keyword', 'In the method below, the parameter is named x, the same as the instance field. What would happen if this.x = x; were replaced with x = x;?', 'public void setX(int x) {
    this.x = x;
}', 'Inside the method body, an unqualified x refers to the parameter (it shadows the field), so x = x; is a no-op on the field.', 'medium', 60, ARRAY['this keyword', 'scope'], 'Assuming Java always knows you mean the field when a parameter shares its name.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'The instance field x would be updated correctly, exactly as before.', false, 'Without this, x on the left refers to the local parameter, not the field.', 0),
  ('B', 'The parameter would be assigned to itself, and the instance field would remain unchanged.', true, 'Inside the method body, an unqualified x refers to the parameter (it shadows the field), so x = x; is a no-op on the field.', 1),
  ('C', 'The code would fail to compile.', false, 'x = x; is legal Java, just logically useless here — it compiles without error.', 2),
  ('D', 'A NullPointerException would be thrown at runtime.', false, 'No object is being dereferenced in a way that could throw NPE here.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'Short-circuit evaluation', 'What is the value of result when x is 0, and why doesn''t this code throw an exception?', 'int x = 0;
boolean result = (x != 0) && (10 / x > 1);', 'Because the left operand of && is false, Java skips evaluating the right operand entirely, avoiding the division by zero.', 'medium', 75, ARRAY['short-circuit evaluation', 'boolean expressions'], 'Believing Java always evaluates every operand of a Boolean expression.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'result is false; && short-circuits after (x != 0) is false, so 10 / x is never evaluated.', true, 'Because the left operand of && is false, Java skips evaluating the right operand entirely, avoiding the division by zero.', 0),
  ('B', 'result is true; Java evaluates both sides regardless.', false, '&& in Java is short-circuiting; it does not always evaluate both operands.', 1),
  ('C', 'The code throws an ArithmeticException.', false, 'The division 10 / x is never reached because of short-circuit evaluation.', 2),
  ('D', 'result is false, but only because 10 / x evaluates to a value less than 1.', false, '10 / x is never evaluated at all in this trace — the short-circuit happens first.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'boolean-expressions-and-if-statements'), 'De Morgan''s laws', 'Which expression is logically equivalent to !(a || b)?', null, 'De Morgan''s law: negating an || distributes the negation and flips it to &&.', 'medium', 50, ARRAY['De Morgan''s laws', 'boolean simplification'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '!a || !b', false, 'This is the equivalent of !(a && b), not !(a || b).', 0),
  ('B', '!a && !b', true, 'De Morgan''s law: negating an || distributes the negation and flips it to &&.', 1),
  ('C', 'a && b', false, 'This has no negations at all and is not equivalent.', 2),
  ('D', '!(a && b)', false, 'This is a different expression, equivalent to !a || !b, not to !(a || b).', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'iteration'), 'Loop tracing', 'What is printed?', 'int sum = 0;
for (int i = 1; i <= 5; i++) {
    sum += i;
}
System.out.println(sum);', 'The loop adds 1 + 2 + 3 + 4 + 5, which totals 15.', 'easy', 50, ARRAY['loop tracing', 'accumulators'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '10', false, 'This would be the sum of 1 through 4, missing the final iteration where i is 5.', 0),
  ('B', '15', true, 'The loop adds 1 + 2 + 3 + 4 + 5, which totals 15.', 1),
  ('C', '20', false, 'This overcounts — it''s not the sum produced by this loop''s bounds.', 2),
  ('D', '5', false, 'This is only the final value of i, not the accumulated sum.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'iteration'), 'Off-by-one errors', 'What happens when this loop runs on an array arr of length 5?', 'for (int i = 0; i <= arr.length; i++) {
    System.out.println(arr[i]);
}', 'When i equals arr.length (5), arr[5] is out of bounds for a length-5 array (valid indices are 0–4).', 'easy', 55, ARRAY['array indexing', 'off-by-one errors'], 'Using <= instead of < when the bound is a length rather than a maximum valid index.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'It prints all 5 elements and stops normally.', false, 'The loop attempts one iteration too many, at i == arr.length.', 0),
  ('B', 'It throws ArrayIndexOutOfBoundsException on the final iteration.', true, 'When i equals arr.length (5), arr[5] is out of bounds for a length-5 array (valid indices are 0–4).', 1),
  ('C', 'It silently skips the invalid index and continues.', false, 'Java does not silently skip invalid array accesses — it throws an exception immediately.', 2),
  ('D', 'It fails to compile.', false, 'This code is syntactically valid; the error occurs at runtime, not compile time.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'writing-classes'), 'Static vs instance', 'Which method can be called without first creating an instance of its class?', 'public class MathHelper {
    public static int square(int n) { return n * n; }
    public int cube(int n) { return n * n * n; }
}', 'static methods belong to the class itself and can be invoked without an object.', 'medium', 55, ARRAY['static methods', 'instance methods'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'square, via MathHelper.square(4)', true, 'static methods belong to the class itself and can be invoked without an object.', 0),
  ('B', 'cube, via MathHelper.cube(4)', false, 'cube is an instance method; calling it this way without an object reference does not compile.', 1),
  ('C', 'Both methods work identically either way.', false, 'Instance methods require an object; only static methods can be called through the class name alone.', 2),
  ('D', 'Neither method can be called without an object.', false, 'square explicitly can, because it is declared static.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'arrays'), 'Array algorithms', 'What is the value of max after this code runs?', 'int[] arr = {3, 1, 4, 1, 5};
int max = arr[0];
for (int i = 1; i < arr.length; i++) {
    if (arr[i] > max) {
        max = arr[i];
    }
}', 'The loop updates max each time it finds a larger element; 5 is the largest value in the array.', 'easy', 60, ARRAY['array traversal', 'finding maximum'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '3', false, 'This is only the initial value of max, before the loop finds a larger element.', 0),
  ('B', '4', false, '4 is replaced once the loop reaches the element 5 later in the array.', 1),
  ('C', '5', true, 'The loop updates max each time it finds a larger element; 5 is the largest value in the array.', 2),
  ('D', '1', false, '1 is never greater than the running max at any point in the trace.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'arraylist'), 'ArrayList removal', 'What does list.remove(1) do here?', 'ArrayList<Integer> list = new ArrayList<>();
list.add(10);
list.add(20);
list.add(30);
list.remove(1);', 'remove(int index) is the index-based overload; index 1 in [10, 20, 30] holds the value 20.', 'hard', 75, ARRAY['ArrayList removal', 'method overloading'], 'Assuming remove(1) always means "remove the value 1" rather than "remove index 1".', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'It removes the value 20, because remove(int) removes by index and index 1 holds 20.', true, 'remove(int index) is the index-based overload; index 1 in [10, 20, 30] holds the value 20.', 0),
  ('B', 'It removes the value 1, searching the list for that value.', false, 'That behavior belongs to remove(Object o), not remove(int), and 1 isn''t even in this list.', 1),
  ('C', 'It throws an exception because 1 is ambiguous.', false, 'Java resolves remove(1) to the int overload unambiguously, since 1 is a primitive int literal.', 2),
  ('D', 'It removes the last element regardless of the argument.', false, 'The argument specifically determines which index is removed.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'arraylist'), 'Removing during traversal', 'What happens when this code runs?', 'ArrayList<String> names = new ArrayList<>(List.of("Ada", "Al", "Bo"));
for (String name : names) {
    if (name.startsWith("A")) {
        names.remove(name);
    }
}', 'Modifying an ArrayList''s structure during a for-each loop invalidates the iterator''s internal state, which Java detects and reports as this exception.', 'hard', 70, ARRAY['ArrayList removal', 'iteration'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'It removes both "Ada" and "Al" successfully.', false, 'The loop throws before it can finish; a for-each loop cannot safely mutate the list it''s iterating over.', 0),
  ('B', 'It throws a ConcurrentModificationException.', true, 'Modifying an ArrayList''s structure during a for-each loop invalidates the iterator''s internal state, which Java detects and reports as this exception.', 1),
  ('C', 'It compiles but silently does nothing.', false, 'The removal attempt actively throws at runtime rather than silently no-op-ing.', 2),
  ('D', 'It fails to compile.', false, 'This code is syntactically valid Java; the failure happens at runtime.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = '2d-arrays'), '2D array traversal', 'What is printed?', 'int[][] grid = {{1, 2}, {3, 4}};
int total = 0;
for (int row = 0; row < grid.length; row++) {
    for (int col = 0; col < grid[row].length; col++) {
        total += grid[row][col];
    }
}
System.out.println(total);', '1 + 2 + 3 + 4 = 10, summed across both rows.', 'medium', 65, ARRAY['2D array traversal', 'nested loops'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '7', false, 'This omits one of the four elements from the sum.', 0),
  ('B', '10', true, '1 + 2 + 3 + 4 = 10, summed across both rows.', 1),
  ('C', '4', false, 'This is only the count of elements, not their sum.', 2),
  ('D', '24', false, 'This would result from multiplying rather than summing the elements.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = '2d-arrays'), 'Boundary checks', 'Why does this code risk an ArrayIndexOutOfBoundsException when row is 0?', 'int above = grid[row - 1][col];', 'When row is 0, row - 1 is -1; negative indices are always invalid in Java arrays.', 'medium', 55, ARRAY['2D arrays', 'boundary conditions'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'row - 1 becomes -1, which is not a valid array index.', true, 'When row is 0, row - 1 is -1; negative indices are always invalid in Java arrays.', 0),
  ('B', 'grid itself is null in this case.', false, 'Nothing in this snippet suggests grid is null — the issue is purely the computed index.', 1),
  ('C', 'col could be out of range instead.', false, 'The question specifically concerns the case where row is 0; col isn''t implicated by that condition.', 2),
  ('D', 'This code cannot throw an exception.', false, 'It absolutely can, and will, when row is 0 and no bounds check guards the access.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'inheritance'), 'Polymorphism', 'What is printed?', 'class Animal {
    public String speak() { return "..."; }
}
class Dog extends Animal {
    public String speak() { return "Woof"; }
}

Animal a = new Dog();
System.out.println(a.speak());', 'Dynamic method dispatch resolves speak() based on the object''s actual runtime type (Dog), not the reference''s declared type (Animal).', 'medium', 65, ARRAY['polymorphism', 'dynamic method dispatch'], 'Believing the compile-time (declared) type determines which overridden method runs.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '...', false, 'This would only print if Java resolved speak() based on the declared type (Animal), which it does not.', 0),
  ('B', 'Woof', true, 'Dynamic method dispatch resolves speak() based on the object''s actual runtime type (Dog), not the reference''s declared type (Animal).', 1),
  ('C', 'It does not compile.', false, 'Assigning a Dog to an Animal reference is legal, since Dog is a subclass of Animal.', 2),
  ('D', 'It throws a ClassCastException.', false, 'No cast is happening here at all — this is a plain upcast assignment, which is always safe.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'inheritance'), 'Overriding vs overloading', 'A subclass defines public String speak(String tone) while the superclass defines public String speak(). What is this an example of?', null, 'Same name, different parameters, in the same or a related class — that''s overloading, not overriding.', 'medium', 60, ARRAY['overriding vs overloading'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'Overriding, since the method name matches.', false, 'Overriding requires an identical parameter list; a different parameter list makes this a distinct method instead.', 0),
  ('B', 'Overloading, since the parameter list differs from the superclass version.', true, 'Same name, different parameters, in the same or a related class — that''s overloading, not overriding.', 1),
  ('C', 'A compiler error, since the superclass already defines speak.', false, 'This is legal; the subclass simply gains an additional speak method alongside the inherited one.', 2),
  ('D', 'Constructor chaining.', false, 'Constructor chaining refers to constructors calling other constructors via this() or super(), unrelated to this scenario.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'recursion'), 'Recursion tracing', 'What is the value of mystery(4)?', 'public static int mystery(int n) {
    if (n <= 0) {
        return 0;
    }
    return n + mystery(n - 1);
}', 'mystery(4) = 4 + mystery(3) = 4 + 3 + mystery(2) = ... = 4 + 3 + 2 + 1 + 0 = 10.', 'hard', 80, ARRAY['recursion tracing', 'base case', 'call stack'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '4', false, 'This is only the first term added; the recursion continues accumulating further terms.', 0),
  ('B', '10', true, 'mystery(4) = 4 + mystery(3) = 4 + 3 + mystery(2) = ... = 4 + 3 + 2 + 1 + 0 = 10.', 1),
  ('C', '24', false, '24 would result from multiplying 4 × 3 × 2 × 1, which is a factorial pattern, not this summing pattern.', 2),
  ('D', '0', false, '0 is only the base case''s return value, reached at the bottom of the recursion, not the final accumulated result.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'recursion'), 'Missing base cases', 'What happens when countDown(5) is called?', 'public static void countDown(int n) {
    System.out.println(n);
    countDown(n - 1);
}', 'Without a base case, each call adds another frame to the call stack until the stack''s limited memory is exhausted.', 'medium', 60, ARRAY['recursion', 'base case', 'StackOverflowError'], 'Assuming recursive calls stop on their own once numbers ''look done'', without an explicit base case.', null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', 'It prints 5, 4, 3, 2, 1 and stops.', false, 'There is no base case to stop the recursion at 1 or 0 — it keeps calling itself indefinitely.', 0),
  ('B', 'It prints decreasing numbers forever (in principle) and eventually throws a StackOverflowError.', true, 'Without a base case, each call adds another frame to the call stack until the stack''s limited memory is exhausted.', 1),
  ('C', 'It fails to compile because there is no return statement.', false, 'The method is void, so it needs no return statement — this compiles fine.', 2),
  ('D', 'It runs once and returns silently.', false, 'The method calls itself unconditionally at the end, so it does not simply run once.', 3)
) as v(label, text, is_correct, explanation, sort_order);
with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = 'arrays'), 'Array algorithms', 'After this code runs, what is arr[0]?', 'int[] arr = {2, 4, 6, 8};
for (int i = 0; i < arr.length / 2; i++) {
    int temp = arr[i];
    arr[i] = arr[arr.length - 1 - i];
    arr[arr.length - 1 - i] = temp;
}', 'This is the standard in-place reversal pattern; index 0 ends up swapped with the original last element, 8.', 'medium', 70, ARRAY['array algorithms', 'reversing'], null, null, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
  ('A', '2', false, 'That was the original value at index 0, before the swap loop ran.', 0),
  ('B', '8', true, 'This is the standard in-place reversal pattern; index 0 ends up swapped with the original last element, 8.', 1),
  ('C', '6', false, '6 ends up at index 1 after reversal, not index 0.', 2),
  ('D', '4', false, '4 ends up at index 2 after reversal, not index 0.', 3)
) as v(label, text, is_correct, explanation, sort_order);

-- ---------------------------------------------------------------------------
-- FRQ Workshop questions
-- ---------------------------------------------------------------------------
with new_frq as (
  insert into frq_questions (unit_id, title, prompt, starter_code, difficulty, estimated_minutes, question_type, published)
  values ((select id from units where slug = 'arrays'), 'SnowfallTracker: Days Above Average', 'A SnowfallTracker object stores one winter''s worth of daily snowfall totals, in inches, in the instance array field dailyTotals. Write the method daysAboveAverage, which returns the number of days on which the snowfall was strictly greater than the average daily snowfall for the whole array.

Assume dailyTotals contains at least one element, and that a working, fully-encapsulated SnowfallTracker class already exists — you are only responsible for the body of daysAboveAverage.', 'public class SnowfallTracker {
    private double[] dailyTotals;

    // constructor and other methods not shown

    /**
     * Returns the number of days in dailyTotals whose snowfall was
     * strictly greater than the average of all days in dailyTotals.
     */
    public int daysAboveAverage() {
        // your code here
    }
}', 'medium', 25, 'guided', true)
  returning id
)
insert into frq_rubric_items (frq_id, description, point_value, sort_order)
select id, v.description, v.points, v.sort_order
from new_frq, (values
  ('Correctly computes the sum of all elements in dailyTotals', 2::numeric, 0),
  ('Correctly computes the average as a floating-point value (sum divided using double arithmetic, not truncated integer division)', 2::numeric, 1),
  ('Traverses the array a second time, comparing each element to the average', 2::numeric, 2),
  ('Correctly counts only elements strictly greater than the average (not >=)', 2::numeric, 3),
  ('Returns the count as an int', 1::numeric, 4)
) as v(description, points, sort_order);
insert into frq_test_cases (frq_id, input_data, expected_output, is_hidden, sort_order)
select (select id from frq_questions where title = 'SnowfallTracker: Days Above Average'), v.input, v.output, v.hidden, v.sort_order
from (values
  ('dailyTotals = {2.0, 4.0, 6.0}  (average = 4.0)', '1  (only 6.0 is above the average)', false, 0),
  ('dailyTotals = {5.0}  (single element)', '0  (5.0 is not strictly greater than its own average)', false, 1),
  ('dailyTotals = {0.0, 0.0, 0.0}', '0  (all equal the average; none is strictly greater)', true, 2),
  ('dailyTotals = {1.0, 2.0, 3.0, 4.0, 100.0}', '1  (average is 22.0; only 100.0 exceeds it)', true, 3)
) as v(input, output, hidden, sort_order);
with new_frq as (
  insert into frq_questions (unit_id, title, prompt, starter_code, difficulty, estimated_minutes, question_type, published)
  values ((select id from units where slug = 'arraylist'), 'RosterTrim: Removing Below a Threshold', 'Write a static method removeBelow that takes an ArrayList<Integer> scores and an int threshold, and removes every element strictly less than threshold from the list, modifying it in place. The method returns nothing.', 'public static void removeBelow(ArrayList<Integer> scores, int threshold) {
    // your code here
}', 'medium', 20, 'standard', true)
  returning id
)
insert into frq_rubric_items (frq_id, description, point_value, sort_order)
select id, v.description, v.points, v.sort_order
from new_frq, (values
  ('Traverses the list in a way that safely allows removal (e.g., iterating backward, or using an explicit index adjustment)', 3::numeric, 0),
  ('Correctly compares each element to threshold using <', 2::numeric, 1),
  ('Calls remove with the correct index-based overload, not the object-based one, or otherwise removes correctly', 2::numeric, 2),
  ('Method has no return statement / matches the void signature', 1::numeric, 3)
) as v(description, points, sort_order);
insert into frq_test_cases (frq_id, input_data, expected_output, is_hidden, sort_order)
select (select id from frq_questions where title = 'RosterTrim: Removing Below a Threshold'), v.input, v.output, v.hidden, v.sort_order
from (values
  ('scores = [50, 72, 65, 90, 40], threshold = 60', 'scores becomes [72, 65, 90]', false, 0),
  ('scores = [10, 20, 30], threshold = 100', 'scores becomes [] (empty)', false, 1),
  ('scores = [], threshold = 50', 'scores remains [] (no exception)', true, 2)
) as v(input, output, hidden, sort_order);
with new_frq as (
  insert into frq_questions (unit_id, title, prompt, starter_code, difficulty, estimated_minutes, question_type, published)
  values ((select id from units where slug = 'recursion'), 'digitSum: Recursive Digit Sum', 'Write a recursive method digitSum(int n) that returns the sum of the digits of a non-negative integer n. For example, digitSum(482) returns 4 + 8 + 2 = 14. You may not use any loops — the repetition must come from recursion.', 'public static int digitSum(int n) {
    // your code here
}', 'hard', 20, 'standard', true)
  returning id
)
insert into frq_rubric_items (frq_id, description, point_value, sort_order)
select id, v.description, v.points, v.sort_order
from new_frq, (values
  ('Correct base case (n < 10 returns n)', 2::numeric, 0),
  ('Correct recursive case combining n % 10 with a recursive call', 3::numeric, 1),
  ('Recursive call passes n / 10, making progress toward the base case', 2::numeric, 2),
  ('No loop is used; solution is genuinely recursive', 1::numeric, 3)
) as v(description, points, sort_order);
insert into frq_test_cases (frq_id, input_data, expected_output, is_hidden, sort_order)
select (select id from frq_questions where title = 'digitSum: Recursive Digit Sum'), v.input, v.output, v.hidden, v.sort_order
from (values
  ('n = 482', '14', false, 0),
  ('n = 7', '7', false, 1),
  ('n = 0', '0', true, 2),
  ('n = 1000', '1', true, 3)
) as v(input, output, hidden, sort_order);

-- ---------------------------------------------------------------------------
-- Badges
-- ---------------------------------------------------------------------------
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Loop Cartographer', 'Traced 25 loops to completion without a tracing error.', 'map', 'loop_traces_correct', 25);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Boolean Logician', 'Mastered compound Boolean expressions and De Morgan''s laws.', 'toggle-left', 'unit_mastery', 3);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Array Archivist', 'Completed every array algorithm drill in the Syntax Café.', 'layout-grid', 'drills_completed_topic', 100);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Class Architect', 'Wrote 10 complete, correctly encapsulated classes.', 'building-2', 'classes_written', 10);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Recursion Scholar', 'Correctly traced 15 recursive call stacks.', 'repeat', 'recursion_traces_correct', 15);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Syntax Sommelier', 'Reached a 7-day Syntax Café streak.', 'flame', 'streak_days', 7);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('FRQ Analyst', 'Completed the rubric review stage on 10 FRQs.', 'clipboard-check', 'frq_rubric_reviews', 10);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Method Master', 'Passed 20 method-header drills without a hint.', 'square-code', 'method_header_drills', 20);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Debugging Detective', 'Correctly identified and fixed 20 logic errors.', 'search', 'error_corrections', 20);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Polymorphism Professional', 'Reached Strong mastery in the Inheritance unit.', 'shuffle', 'unit_mastery_level', 5);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Reference Wrangler', 'Bookmarked and reviewed 15 Java Reference Library entries.', 'bookmark', 'reference_bookmarks', 15);
insert into badges (name, description, icon, requirement_type, requirement_value) values ('Two-Dimensional Thinker', 'Completed every 2D array drill and MCQ.', 'grid-3x3', 'unit_completed', 8);

