// One-off generator: turns the TypeScript content in lib/content/** into
// database/seed/seed.sql. Run with: node scripts/generate-seed.ts
// (Node 22's built-in TypeScript stripping handles the `import type`s below
// without a build step — this script has zero runtime imports otherwise.)

import { units } from "../lib/content/units.ts";
import { syntaxDrills } from "../lib/content/syntax-drills.ts";
import { mcqQuestions } from "../lib/content/mcq-questions.ts";
import { frqQuestions } from "../lib/content/frq-questions.ts";
import { referenceEntries } from "../lib/content/reference-library.ts";
import { badgeDefinitions } from "../lib/content/badges.ts";
import { integerDivisionAndModulusLesson } from "../lib/content/lessons/integer-division-and-modulus.ts";
import { writeFileSync } from "node:fs";

function sql(str: string): string {
  return `'${str.replace(/'/g, "''")}'`;
}

function jsonb(value: unknown): string {
  return `${sql(JSON.stringify(value))}::jsonb`;
}

function textArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `ARRAY[${values.map((v) => sql(v)).join(", ")}]`;
}

const lines: string[] = [];
lines.push("-- ============================================================================");
lines.push("-- JavaChip — Seed data (generated by scripts/generate-seed.ts)");
lines.push("-- Seeds course content only. Demo accounts, classes, and assignments require");
lines.push("-- real auth.users rows — see database/seed/README.md.");
lines.push("-- ============================================================================");
lines.push("");
lines.push("insert into courses (title, description, slug, published) values");
lines.push(
  `  ('AP Computer Science A', 'JavaChip''s complete, original AP CSA curriculum across all ten College Board units.', 'ap-csa', true);`
);
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Units");
lines.push("-- ---------------------------------------------------------------------------");
for (const u of units) {
  lines.push(
    `insert into units (course_id, unit_number, title, slug, description, estimated_minutes, sort_order, published) values ((select id from courses where slug = 'ap-csa'), ${u.unitNumber}, ${sql(u.title)}, ${sql(u.slug)}, ${sql(u.description)}, ${u.estimatedMinutes}, ${u.unitNumber}, true);`
  );
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Lessons (stubs for every unit; the first lesson of Unit 1 is fully authored)");
lines.push("-- ---------------------------------------------------------------------------");
for (const u of units) {
  u.lessons.forEach((l, idx) => {
    lines.push(
      `insert into lessons (unit_id, title, slug, description, estimated_minutes, sort_order, published) values ((select id from units where slug = ${sql(u.slug)}), ${sql(l.title)}, ${sql(l.slug)}, ${sql(l.title + " — part of the " + u.title + " unit.")}, ${l.estimatedMinutes}, ${idx}, ${l.built});`
    );
  });
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Unit vocabulary");
lines.push("-- ---------------------------------------------------------------------------");
for (const u of units) {
  for (const v of u.vocabulary) {
    lines.push(
      `insert into vocabulary_terms (unit_id, term, definition) values ((select id from units where slug = ${sql(u.slug)}), ${sql(v.term)}, ${sql(v.definition)});`
    );
  }
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Fully authored lesson: Integer Division and Modulus — one lesson_sections");
lines.push("-- row per part of the 26-part lesson structure.");
lines.push("-- ---------------------------------------------------------------------------");
{
  const lsn = integerDivisionAndModulusLesson;
  const lessonRef = `(select id from lessons where slug = ${sql(lsn.slug)})`;
  const sections: [string, string, unknown][] = [
    ["hook", "Real-World Hook", lsn.hook],
    ["objectives", "Learning Objectives", lsn.objectives],
    ["prerequisites", "Prerequisite Knowledge", lsn.prerequisites],
    ["vocabulary", "Vocabulary", lsn.vocabulary],
    ["explanation", "Detailed Explanation", lsn.explanation],
    ["syntax_template", "Syntax Template", lsn.syntaxTemplate],
    ["annotated_example", "Annotated Java Example", lsn.annotatedExample],
    ["line_by_line", "Line-by-Line Breakdown", lsn.lineByLineBreakdown],
    ["execution_trace", "Visual Execution Trace", lsn.executionTrace],
    ["variable_state_table", "Variable-State Table", lsn.variableStateTable],
    ["memory_note", "Memory / Reference Note", lsn.memoryNote],
    ["common_mistakes", "Common Mistakes", lsn.commonMistakes],
    ["compiler_errors", "Compiler-Error Examples", lsn.compilerErrorExamples],
    ["logic_errors", "Logic-Error Examples", lsn.logicErrorExamples],
    ["predict_output", "Predict-the-Output Questions", lsn.predictOutputQuestions],
    ["fill_in_code", "Fill-in-the-Code Questions", lsn.fillInCodeQuestions],
    ["code_ordering", "Code-Ordering Activity", lsn.codeOrderingActivity],
    ["error_correction", "Error-Correction Activity", lsn.errorCorrectionActivity],
    ["coding_challenge", "Short Coding Challenge", lsn.shortCodingChallenge],
    ["mcq_mini_set", "MCQ Mini-Set", lsn.mcqMiniSet],
    ["reflection", "Reflection", lsn.reflectionPrompts],
    ["mastery_check", "Mastery Check", lsn.masteryCheck],
    ["summary", "Summary", lsn.summary],
    ["related_links", "Related Reference Links", lsn.relatedReferenceLinks],
    ["next_lesson", "Suggested Next Lesson", lsn.suggestedNextLesson],
  ];
  sections.forEach(([type, title, content], idx) => {
    lines.push(
      `insert into lesson_sections (lesson_id, section_type, title, content, sort_order) values (${lessonRef}, ${sql(type)}, ${sql(title)}, ${jsonb(content)}, ${idx});`
    );
  });
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Java Reference Library entries (stored as syntax_templates)");
lines.push("-- ---------------------------------------------------------------------------");
for (const r of referenceEntries) {
  lines.push(
    `insert into syntax_templates (topic, title, description, template_code, example_code, common_mistake, difficulty) values (${sql(r.category)}, ${sql(r.name)}, ${sql(r.definition)}, ${sql(r.syntax)}, ${sql(r.example)}, ${sql(r.commonMistake)}, 'easy');`
  );
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Syntax Café drills");
lines.push("-- ---------------------------------------------------------------------------");
for (const d of syntaxDrills) {
  lines.push(
    `insert into syntax_questions (unit_id, topic, drill_type, prompt, starter_code, correct_answer, explanation, difficulty) values ((select id from units where slug = ${sql(d.unitSlug)}), ${sql(d.topic)}, ${sql(d.drillType)}, ${sql(d.prompt)}, ${d.starterCode ? sql(d.starterCode) : "null"}, ${sql(d.correctAnswer)}, ${sql(d.explanation)}, ${sql(d.difficulty)});`
  );
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- MCQ Question Bank");
lines.push("-- ---------------------------------------------------------------------------");
for (const q of mcqQuestions) {
  lines.push(
    `with new_question as (
  insert into mcq_questions (unit_id, topic, prompt, code, explanation, difficulty, estimated_seconds, skills_tested, common_misconception, hint, published)
  values ((select id from units where slug = ${sql(q.unitSlug)}), ${sql(q.topic)}, ${sql(q.prompt)}, ${q.code ? sql(q.code) : "null"}, ${sql(q.choices.find((c) => c.correct)!.explanation)}, ${sql(q.difficulty)}, ${q.estimatedSeconds}, ${textArray(q.skillsTested)}, ${q.commonMisconception ? sql(q.commonMisconception) : "null"}, ${q.hint ? sql(q.hint) : "null"}, true)
  returning id
)
insert into mcq_choices (question_id, choice_label, choice_text, is_correct, explanation, sort_order)
select id, v.label, v.text, v.is_correct, v.explanation, v.sort_order
from new_question, (values
${q.choices.map((c, i) => `  (${sql(c.label)}, ${sql(c.text)}, ${c.correct}, ${sql(c.explanation)}, ${i})`).join(",\n")}
) as v(label, text, is_correct, explanation, sort_order);`
  );
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- FRQ Workshop questions");
lines.push("-- ---------------------------------------------------------------------------");
for (const f of frqQuestions) {
  lines.push(
    `with new_frq as (
  insert into frq_questions (unit_id, title, prompt, starter_code, difficulty, estimated_minutes, question_type, published)
  values ((select id from units where slug = ${sql(f.unitSlug)}), ${sql(f.title)}, ${sql(f.prompt)}, ${sql(f.starterCode)}, ${sql(f.difficulty)}, ${f.estimatedMinutes}, ${sql(f.questionType)}, true)
  returning id
)
insert into frq_rubric_items (frq_id, description, point_value, sort_order)
select id, v.description, v.points, v.sort_order
from new_frq, (values
${f.rubric.map((r, i) => `  (${sql(r.description)}, ${r.points}::numeric, ${i})`).join(",\n")}
) as v(description, points, sort_order);`
  );
  lines.push(
    `insert into frq_test_cases (frq_id, input_data, expected_output, is_hidden, sort_order)
select (select id from frq_questions where title = ${sql(f.title)}), v.input, v.output, v.hidden, v.sort_order
from (values
${f.testCases.map((t, i) => `  (${sql(t.inputDescription)}, ${sql(t.expectedOutput)}, ${t.hidden}, ${i})`).join(",\n")}
) as v(input, output, hidden, sort_order);`
  );
}
lines.push("");

lines.push("-- ---------------------------------------------------------------------------");
lines.push("-- Badges");
lines.push("-- ---------------------------------------------------------------------------");
for (const b of badgeDefinitions) {
  lines.push(
    `insert into badges (name, description, icon, requirement_type, requirement_value) values (${sql(b.name)}, ${sql(b.description)}, ${sql(b.icon)}, ${sql(b.requirementType)}, ${b.requirementValue});`
  );
}
lines.push("");

writeFileSync(new URL("../database/seed/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote database/seed/seed.sql (${lines.length} lines)`);
